### ISSUE TITLE
smtprelay: restart when certificate is updated

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/infralib#1]

**Comment by q3k** [comment]
We could expose the TLS secret into the smtprelay pod as a volume mount, and make smtprelay reload the data from disk on change. Since we're already maintaining an smtprelay fork, that might be the best solution.

The alternative is some sort of kind (there exist some generic implementations, IIRC) which would kill the smtprelay pod any time it notices its env vars are not 'up to date', but that's not ideal IMO.

**Comment by lorenz** [comment]
I have https://git.dolansoft.org/dolansoft/kinit if you are concerned with resource usage. Should also work with SIGTERM if the process doesn't have a reload signal.

**Comment by leoluk** [comment]
I actually *thought* I had taken care of this by using environment variables vs. a volume mount, which I expected would cause the pod to restart, but clearly I was wrong :-)

https://kubernetes.io/docs/concepts/configuration/secret/#environment-variables-are-not-updated-after-a-secret-update

@lorenz my user account can't access that

**Comment by leoluk** [comment]
No more smtprelay!
